apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpdesk-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helpdesk-api
  template:
    metadata:
      labels:
        app: helpdesk-api
    spec:
      containers:
        - name: helpdesk-api
          image: ghcr.io/mouaadchakir/devops-helpdesk-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: helpdesk-config
            - secretRef:
                name: helpdesk-secret
