apiVersion: v1
kind: ConfigMap
metadata:
  name: helpdesk-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/helpdesk_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SPRING_JPA_OPEN_IN_VIEW: "false"
