apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - app-deployment.yaml
  - app-service.yaml
